# Deploys Platform API, MongoDB and Portal 
- name: Create filesystem
  hosts: mount_ebs

  tasks:
    - include_vars: "{{ lookup('env','SOLINVENTORY_CONFIG') or '../vars' }}/ansible_vars.yml"
    - include_vars: "{{sensitive_ansible_vars_file}}"
    - include_vars: "{{generated_infrastructure_vars_file}}"

    - name: Create filesystem on EBS devices /dev/xvdh on box1 
      filesystem:
        fstype: ext4
        dev: /dev/xvdh
      become: yes

    - name: Create mount point /data
      file:
        path: /data
        owner: root
        group: root
        state: directory
      become: yes

    - name: Mount filesystem
      mount:
        path: /data
        src: /dev/xvdh
        fstype: ext4
        state: mounted
      become: yes  

    - name: Create file /data/readme.md
      file:
        path: /data/readme.md
        state: touch
      become: yes

- name: Install Docker hosts
  hosts: docker_hosts
  roles:
    - dockerhost

- name: Install MySQL Client on all boxes
  hosts: all
  tasks:
    - name: Install MySQL Client
      apt:
        name: ['mysql-client-5.7', 'python-mysqldb', 'libmysqlclient-dev']
        state: present
        update_cache: yes
      become: yes

- name: Install and start platform_api
  hosts: platform_api
  roles:
    - platform-api

  tasks:
    - name: copy
      copy:
        src: files/check_platform_api.sh
        dest: /data/platform-api/docker
        owner: root
        group: root
        mode: 0744
      become: yes

    - name: execute script to check platform-api status
      script: files/check_platform_api.sh /data/platform-api/docker platform-api-server-2
      become: yes

    - name: check server status 
      stat: 
        path: /data/platform-api/docker/tmp/SERVER_INITIALIZED
      register: check_result

    - debug: msg="PLATFORM-API successfully initialized, up and running"
      when: check_result.stat.exists

    - debug: msg="PLATFORM-API NOT UP AND / OR INITIALIZED"
      when: not check_result.stat.exists


